### ISSUE TITLE
TypeError: Object s���h½�▒▒^�# has no method 'charCodeAt'

### ISSUE THREAD

**Issue by omoss** [mscdex/node-oscar#12]
I get the following error while trying to run `test.js` in a blank project using Node v0.10.25:

```
/home/user/oscarTest/node_modules/oscar/oscar.js:2676
          hash[i] = oldhash.charCodeAt(i);
                            ^
TypeError: Object s���h½�▒▒^�# has no method 'charCodeAt'
    at OscarConnection._login (/home/user/oscarTest/node_modules/oscar/oscar.js:2676:29)
    at /home/user/oscarTest/node_modules/oscar/oscar.js:2653:62
    at process._tickCallback (node.js:415:13)
```

username and password have been changed in `test.js` to valid values.

**Comment by omoss** [comment]
I applied the changes from the latest commit d98acf84f30a9eeaf53d310fb3bdf2008296dd4b manually and it kinda works again.

it will connect and receive messages, but the `sendIM` function fails due to `_createFLAP`:

```
TypeError: Cannot read property 'seqNum' of undefined
    at OscarConnection._createFLAP (/home/user/oscarTest/node_modules/oscar/oscar.js:2941:35)
    at OscarConnection.sendIM (/home/user/oscarTest/node_modules/oscar/oscar.js:168:19)
```

The `_createFlap` function appears to be receiving an undefined `conn` parameter when called from `sendIM` on line 168. 

`sendIM` is sending `self._state.connections.main` as the `conn` parameter, and `self._state.connections.main` appears to be undefined after login.
