### ISSUE TITLE
oscar/oscar.js:2214  TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by CryptexDHT** [mscdex/node-oscar#14]
#    Please help

```
oscar/oscar.js:2214
for (var i=0,groups=Object.keys(items[0x01]),len=groups.length,gro

TypeError: Object.keys called on non-object
at Function.keys (native)
at OscarConnection._parseSNAC (app/node_modules/oscar/oscar.js:2214:40)
at Socket.data_handler (app/node_modules/oscar/oscar.js:746:14)
at Socket.<anonymous> (app/node_modules/oscar/oscar.js:872:72)
at Socket.EventEmitter.emit (events.js:95:17)
at Socket.<anonymous> (_stream_readable.js:746:14)
at Socket.EventEmitter.emit (events.js:92:17)
at emitReadable_ (_stream_readable.js:408:10)
at emitReadable (_stream_readable.js:404:5)
at readableAddChunk (_stream_readable.js:165:9)
```

**Comment by CryptexDHT** [comment]
This error appear only in new ICQ account. But after i added one user in roster list to this UIN, using Pidgin, this error is disappeared.
