### ISSUE TITLE
Connection reset after some time

### ISSUE THREAD

**Issue by j6s** [mscdex/node-oscar#16]
Hello,

as i mentioned in an other ticket, i am building a constantly running bot. However i get a Connection reset after some time (ECONNRESET). I have not yet analyzed the length, but it is somewhere around 10-20minutes of inactivity.

Is there some sort of "ping" function, to signalize, that the client is still active, so the connection is not being reset?

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

```

**Comment by j6s** [comment]
Seems to be a duplicate of #3
