### ISSUE TITLE
TypeError: Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by bryanhelmig** [mscdex/node-oscar#7]
```
http.js:1093
  s.on('free', onFree);
    ^
TypeError: Cannot call method 'on' of undefined
    at Agent.createSocket (http.js:1093:5)
    at Agent.addRequest (http.js:1070:23)
    at new ClientRequest (http.js:1205:16)
    at Object.exports.request (http.js:1585:10)
    at Request.request.self.start (/Users/bryan/Dropbox/web-www/zapim/node_modules/request/main.js:348:32)
    at Request.write (/Users/bryan/Dropbox/web-www/zapim/node_modules/request/main.js:561:28)
    at Request.request (/Users/bryan/Dropbox/web-www/zapim/node_modules/request/main.js:530:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

Easy fix, seems like the overloading of the connect() method on socket is what messes it up, simply comment out the overloading:

``` javascript
var _oldStreamConnect = net.Stream.prototype.connect;
net.Stream.prototype.connect = function(port, host) {
  this.remoteAddress = host;
  this.remotePort = port;
  _oldStreamConnect.apply(this, Array.prototype.slice.call(arguments));
};
```

Should be:

``` javascript
// var _oldStreamConnect = net.Stream.prototype.connect;
// net.Stream.prototype.connect = function(port, host) {
//   this.remoteAddress = host;
//   this.remotePort = port;
//   _oldStreamConnect.apply(this, Array.prototype.slice.call(arguments));
// };
```

**Comment by mscdex** [comment]
This code was originally for node 0.4.x where Socket.remoteAddress existed only for incoming connections and Socket.remotePort did not exist at all.

I guess I can bump the node requirement to 0.6.x now.

**Comment by mikeknoop** [comment]
FYI repo with changes (commented out): https://github.com/zapier/node-oscar/

**Comment by bryanhelmig** [comment]
Very nice to see a response, thanks a bunch for making this lib. This combined with the other outstanding pull request makes this lib compatible with Node 0.8.1 (at least in our testing and use, which may not be exhaustive).

**Comment by mscdex** [comment]
Ok, I pushed a couple of fixes, if master now works for you, I will publish a new version.
